### PR TITLE
Feature #187 - Changed default styling of action buttons

### PR DESCRIPTION
**Pull request by bartvig**
Changed styling of action buttons to "block" and removed action-buttons-is-visible.

http://platform.dandigbib.org/issues/187

### CODE REVIEW

**Comment by cableman** [comment]
The sass needs to be complied into css.

**Comment by guddo** [comment]
While I was at it, I rebased this PR as well: https://github.com/ding2/ddbasic/pull/19.

**Comment by cableman** [comment]
Please rebase, so it can be merged :-)

**Comment by cableman** [comment]
Merged into the consolidated repository

**Pull request closed without merging**
