### PR TITLE
Issue #970 by holt83: Fixed position for place2book links for events.

### PR DESCRIPTION
**Pull request by holt83**
…fo div element

### CODE REVIEW

**Comment by holt83** [comment]
My editor removed some trailing whitespaces. If this is a problem let me know

**Comment by cableman** [comment]
Code is approved, but commit message needs a little more. It should have the format:

Issue #970 by holt83: Fixed position for place2book links for events.

Please see https://www.drupal.org/node/52287

**Comment by holt83** [comment]
I updated the commit message to the suggested format.

**Comment by kasperg** [comment]
Thanks. Reviewed, approved and ready for merge.

**Pull request merged**
